services:
- type: pserv
  name: miles-soap-staging-db
  plan: standard
  env: docker
  autoDeploy: false
  disk:
    name: miles-soap-staging-db-disk
    mountPath: /var/lib/mysql
    sizeGB: 10
  envVars:
  - fromGroup: miles-soap-staging-db-env

envVarGroups:
- name: miles-soap-staging-db-env
  envVars:
  - key: MYSQL_DATABASE
    value: miles-soap-staging-db
  - key: MYSQL_USER
    value: miles-soap-staging-db-user
  - key: MYSQL_PASSWORD
    generateValue: true
  - key: MYSQL_ROOT_PASSWORD
    generateValue: true
